/**
 * newsBot.js
 * ---------------------------------------------------------
 * Auto-posts to #spideynq-gems:
 *   1. Morning brief (today's econ calendar + headlines, written up
 *      as a full "Today's Watch" analysis — not just raw data)
 *   2. Evening-before warning (tomorrow's high-impact econ events)
 *
 * Data sources:
 *   - Finnhub (free): economic calendar + market headlines
 *   - Anthropic API: turns that raw data into the "Today's Watch" writeup
 *     — the context, the "how NQ could move" scenarios, the TL;DR.
 *     Raw calendar data alone can't produce that; this is the step
 *     that actually writes it, in your voice/format.
 *
 * Wire-up: call initNewsBot(client) once from your main bot file
 * (same place you initialize your other scheduled features).
 * ---------------------------------------------------------
 */

const cron = require("node-cron");
const { EmbedBuilder } = require("discord.js");
const config = require("./config"); // pulls CHANNEL_ID + API keys from your existing config.js

const FINNHUB_BASE = "https://finnhub.io/api/v1";
const GEMINI_MODEL = "gemini-2.0-flash"; // free tier — swap models in Google AI Studio if you want

// ---- helpers -------------------------------------------------

function todayISO(offsetDays = 0) {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split("T")[0]; // YYYY-MM-DD
}

function friendlyDate(offsetDays = 0) {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
}

async function fetchJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed: ${res.status} ${res.statusText} — ${url}`);
  return res.json();
}

// Economic calendar for a single date, US-focused. Returns ALL impact levels,
// each labeled with its folder color (matches standard red/yellow/gray convention).
function folderLabel(impact) {
  if (impact === "high") return "🔴 Red Folder";
  if (impact === "medium") return "🟡 Yellow Folder";
  return "⚪ No Impact";
}

async function getEconomicEvents(dateISO) {
  const url = `${FINNHUB_BASE}/calendar/economic?from=${dateISO}&to=${dateISO}&token=${config.FINNHUB_API_KEY}`;
  const data = await fetchJSON(url);
  const events = data.economicCalendar || data.events || [];
  return events
    .filter((e) => e.country === "US")
    .map((e) => ({
      time: e.time || "TBD",
      event: e.event,
      forecast: e.estimate ?? e.forecast ?? null,
      previous: e.prev ?? e.previous ?? null,
      impact: e.impact, // "high" | "medium" | "low"
      folder: folderLabel(e.impact),
    }));
}

// Top general market headlines
async function getMarketHeadlines(limit = 8) {
  const url = `${FINNHUB_BASE}/news?category=general&token=${config.FINNHUB_API_KEY}`;
  const data = await fetchJSON(url);
  return (data || []).slice(0, limit).map((h) => ({
    headline: h.headline,
    summary: h.summary,
    url: h.url,
    source: h.source,
  }));
}

// ---- the writeup, generated by Claude from the raw data ------------

const BRIEF_SYSTEM_PROMPT = `You write the daily "Today's Watch" market brief for a Nasdaq futures (NQ) trading Discord community. Match this exact structure and tone — direct, sharp, no fluff, no generic disclaimers baked into the body copy:

📊 Today's Watch — [Weekday Month Day]
The numbers that matter for NQ:

* [time] — [event] (forecast [X]) — [folder label, e.g. 🔴 Red Folder]
* [time] — [event] (forecast [X]) — [folder label]
...
(Only list 🔴 Red Folder and 🟡 Yellow Folder events in this main list. Do not include ⚪ No Impact events here.)

[1-2 short paragraphs of real context on the single most important item today — what it actually is, why it matters right now, any relevant backstory from the headlines provided. Skip this if nothing in the provided data warrants it.]

What it means: [1-2 sentences connecting today's data to the recent trend]

How NQ could move:

* 🟢 [bullish scenario tied to the actual data provided]
* 🔴 [bearish scenario tied to the actual data provided]
* [any wildcard/headline risk worth flagging, if the provided headlines support one]

TL;DR: [one tight closing line — what's the single biggest thing to watch today and why]

Also today (⚪ no impact): [one short line listing any low/no-impact events by name only, comma-separated — skip this whole line if there are none]

CRITICAL RULES:
- Only use facts present in the data you're given below. Never invent forecasts, names, or events not present in the input. If the input is thin, write a shorter brief rather than padding with invented detail.
- Red and Yellow folder events get the full treatment above. No Impact (⚪) events only ever appear in the single "Also today" line at the very end — never in the main numbered list, never analyzed.
- This is scenario analysis, not a prediction or trading advice — phrase the "How NQ could move" section as conditional possibilities, not certainties.
- Keep total length under 1900 characters so it fits cleanly in a Discord embed.`;

async function generateDailyBrief(dateISO, events, headlines) {
  const inputData = {
    date: friendlyDate(0),
    economic_events: events,
    market_headlines: headlines,
  };

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${config.GEMINI_API_KEY}`;

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      system_instruction: { parts: [{ text: BRIEF_SYSTEM_PROMPT }] },
      contents: [
        {
          role: "user",
          parts: [{ text: `Here's today's data:\n\n${JSON.stringify(inputData, null, 2)}` }],
        },
      ],
      generationConfig: { maxOutputTokens: 700 },
    }),
  });

  if (!res.ok) {
    throw new Error(`Gemini API error: ${res.status} ${res.statusText}`);
  }

  const data = await res.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  return text || null;
}

// ---- formatting -----------------------------------------------

function buildMorningEmbed(briefText) {
  return new EmbedBuilder()
    .setColor(0xb10f1c)
    .setDescription(briefText)
    .setTimestamp()
    .setFooter({ text: "Auto-posted by Spidey Assistant — not trading advice" });
}

// Fallback if Gemini fails: raw data, no narrative, but still useful and still posted.
function buildFallbackEmbed(dateISO, events, headlines) {
  const embed = new EmbedBuilder()
    .setTitle(`📊 Today's Watch — ${friendlyDate(0)}`)
    .setColor(0xb10f1c)
    .setTimestamp()
    .setFooter({ text: "Auto-posted by Spidey Assistant — full write-up unavailable today, raw data only" });

  const redYellow = events.filter((e) => e.impact === "high" || e.impact === "medium");
  const noImpact = events.filter((e) => e.impact !== "high" && e.impact !== "medium");

  if (redYellow.length) {
    const lines = redYellow
      .map((e) => `**${e.time}** — ${e.event}${e.forecast != null ? ` (forecast ${e.forecast})` : ""} — ${e.folder}`)
      .join("\n");
    embed.addFields({ name: "The numbers that matter for NQ", value: lines });
  } else {
    embed.addFields({ name: "The numbers that matter for NQ", value: "Nothing red or yellow folder today." });
  }

  if (noImpact.length) {
    embed.addFields({ name: "⚪ Also today (no impact)", value: noImpact.map((e) => e.event).join(", ") });
  }

  if (headlines.length) {
    const headlineLines = headlines.slice(0, 5).map((h) => `• [${h.headline}](${h.url})`).join("\n");
    embed.addFields({ name: "📰 Headlines", value: headlineLines });
  }

  return embed;
}

function buildEveningWarningEmbed(tomorrowEvents) {
  const embed = new EmbedBuilder()
    .setTitle("⚠️ Heads Up — Tomorrow's Market Movers")
    .setColor(0x111111)
    .setTimestamp()
    .setFooter({ text: "Auto-posted by Spidey Assistant — not trading advice" });

  const redYellow = tomorrowEvents.filter((e) => e.impact === "high" || e.impact === "medium");
  const noImpact = tomorrowEvents.filter((e) => e.impact !== "high" && e.impact !== "medium");

  let description = "";
  if (redYellow.length) {
    description += redYellow
      .map((e) => `**${e.time}** — ${e.event}${e.forecast != null ? ` (forecast ${e.forecast})` : ""} — ${e.folder}`)
      .join("\n");
  } else {
    description += "Nothing red or yellow folder scheduled for tomorrow.";
  }
  if (noImpact.length) {
    description += `\n\n⚪ Also tomorrow (no impact): ${noImpact.map((e) => e.event).join(", ")}`;
  }

  embed.setDescription(description);
  return embed;
}

// ---- posting ----------------------------------------------------

async function postToNewsChannel(client, embed) {
  const channel = await client.channels.fetch(config.NEWS_CHANNEL_ID);
  if (!channel) {
    console.error("News bot: could not find channel with ID", config.NEWS_CHANNEL_ID);
    return;
  }
  await channel.send({ embeds: [embed] });
}

// Private heads-up to you only — never posted publicly. Matches your existing
// pattern of keeping admin/system alerts out of member-facing channels.
async function alertOwner(client, message) {
  try {
    if (!config.OWNER_ID) return; // skip silently if not configured
    const owner = await client.users.fetch(config.OWNER_ID);
    await owner.send(`⚠️ News bot: ${message}`);
  } catch (err) {
    console.error("News bot: failed to DM owner alert:", err);
  }
}

async function runMorningPost(client) {
  const dateISO = todayISO(0);
  let events = [];
  let headlines = [];

  try {
    [events, headlines] = await Promise.all([
      getEconomicEvents(dateISO),
      getMarketHeadlines(8),
    ]);
  } catch (err) {
    console.error("News bot — data fetch failed, skipping today's post:", err);
    await alertOwner(client, "Couldn't fetch Finnhub data this morning — no post went out. Check Railway logs.");
    return;
  }

  // Try the full Gemini writeup. If it fails for any reason (quota, outage,
  // bad response), fall back to a raw-data post instead of posting nothing.
  try {
    const briefText = await generateDailyBrief(dateISO, events, headlines);
    if (!briefText) throw new Error("Gemini returned empty response");
    const embed = buildMorningEmbed(briefText);
    await postToNewsChannel(client, embed);
  } catch (err) {
    console.error("News bot — Gemini writeup failed, posting fallback:", err);
    const fallbackEmbed = buildFallbackEmbed(dateISO, events, headlines);
    await postToNewsChannel(client, fallbackEmbed);
    await alertOwner(client, "Gemini writeup failed this morning — posted the raw-data fallback instead. Worth checking your Gemini API key/quota.");
  }
}

async function runEveningWarning(client) {
  try {
    const tomorrowEvents = await getEconomicEvents(todayISO(1));
    const embed = buildEveningWarningEmbed(tomorrowEvents);
    await postToNewsChannel(client, embed);
  } catch (err) {
    console.error("News bot — evening warning failed:", err);
    await alertOwner(client, "Evening warning post failed — check Railway logs.");
  }
}

// ---- scheduling ---------------------------------------------------

function initNewsBot(client) {
  // Morning brief — 7:30 AM ET, weekdays
  cron.schedule("30 7 * * 1-5", () => runMorningPost(client), { timezone: "America/New_York" });

  // Evening-before warning — 6:00 PM ET, Sunday–Thursday (covers Mon–Fri trading days)
  cron.schedule("0 18 * * 0-4", () => runEveningWarning(client), { timezone: "America/New_York" });

  console.log("News bot scheduled: morning brief 7:30 AM ET, evening warning 6:00 PM ET (Sun–Thu).");
}

module.exports = { initNewsBot, runMorningPost, runEveningWarning };

